### ISSUE TITLE
Hi,did it have a iPhone version?

### ISSUE THREAD

**Issue by zhoupIT** [henrybetts/EOSFramework#2]

**Comment by henrybetts** [comment]
As far as I'm aware, the Canon EDSDK only supports Windows and MacOS (and probably only using USB, no wifi) i'm afraid.

**Comment by zhoupIT** [comment]
but it supports Android

**Comment by henrybetts** [comment]
Source? I know there are a few remote control apps out there, but Canon doesn't provide a mobile SDK, therefore you would have to reverse engineer the protocol in order to implement it.

**Comment by zhoupIT** [comment]
@henrybetts https://github.com/crazymaik/remoteyourcam-usb This is a android version,but i don't know java,you can try it,i expect the good news from you.

**Comment by zhoupIT** [comment]
@henrybetts Is there any discovery?
